In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('22pca.csv')
df

평균기온  최저기온  최고기온   일강수량  최대순간풍속  최대순간풍속풍향  최대풍속  최대풍속풍향  평균풍속  최다풍향  ...  \
0    -4.3 -10.2   2.3    0.0     4.5        70   2.8      20   1.5    50  ...   
1    -1.3  -5.2   3.0    0.3     8.1       290   4.6     290   2.3    50  ...   
2    -1.9  -8.0   2.5    0.0     6.9       270   4.1     250   1.8   270  ...   
3    -2.5  -5.6   1.0    0.0     6.8       270   4.2     250   2.4   290  ...   
4    -2.8  -7.8   1.9    0.0     4.2        50   2.9      50   1.7    50  ...   
..    ...   ...   ...    ...     ...       ...   ...     ...   ...   ...  ...   
176  26.5  24.8  28.1    0.0     8.5       230   5.0     180   2.6   180  ...   
177  26.8  25.4  28.1    6.1    13.7       200   6.0     200   2.8   200  ...   
178  26.9  25.7  27.9    6.3    20.9       180   9.9     200   5.8   200  ...   
179  25.1  24.4  26.1   37.8    17.3       180   9.0     200   4.1   200  ...   
180  22.3  21.2  24.5  176.2     9.4        70   4.6      50   2.3    50  ...   

     일최심신적설  일 미세먼지 농도(㎍/㎥)  휴일여부  강수여부  적설여부  요일  계절  month  day  영등포구  
0       0.0            34.0     1   0.0   0.0   5   4      1    1  2010  
1       0.5            42.0     0   1.0   1.0   6   4      1    2  2065  
2       0.0            28.0     0   0.0   0.0   0   4      1    3  4356  
3       0.0            37.0     0   0.0   0.0   1   4      1    4  4474  
4       0.0            52.0     0   0.0   0.0   2   4      1    5  4665  
..      ...             ...   ...   ...   ...  ..  ..    ...  ...   ...  
176     0.0            23.0     0   0.0   0.0   6   2      6   26  9246  
177     0.0            12.0     0   1.0   0.0   0   2      6   27  8155  
178     0.0            18.0     0   1.0   0.0   1   2      6   28  9134  
179     0.0            14.0     0   1.0   0.0   2   2      6   29  4408  
180     0.0             0.0     0   1.0   0.0   3   2      6   30   743  

[181 rows x 27 columns]

In [3]:
# 1. 기온 part
columns = ['평균기온', '최저기온', '최고기온', '평균이슬점온도']
df_temparature = pd.DataFrame(df, columns = columns)
df_temparature['영등포구'] = df['영등포구']
df_temparature

평균기온  최저기온  최고기온  평균이슬점온도  영등포구
0    -4.3 -10.2   2.3    -14.4  2010
1    -1.3  -5.2   3.0     -8.8  2065
2    -1.9  -8.0   2.5     -9.3  4356
3    -2.5  -5.6   1.0    -11.8  4474
4    -2.8  -7.8   1.9    -12.5  4665
..    ...   ...   ...      ...   ...
176  26.5  24.8  28.1     23.1  9246
177  26.8  25.4  28.1     23.8  8155
178  26.9  25.7  27.9     23.4  9134
179  25.1  24.4  26.1     24.3  4408
180  22.3  21.2  24.5     22.1   743

[181 rows x 5 columns]

In [4]:
temparature_scaled = StandardScaler().fit_transform(df_temparature.iloc[:,:-1])
temparature_scaled

array([[-1.44698741, -1.59000621, -1.27569512, -1.49569837],
       [-1.15054743, -1.09854284, -1.20791128, -0.98627637],
       [-1.20983543, -1.37376233, -1.25632831, -1.03176048],
       [-1.26912342, -1.13785991, -1.4015794 , -1.25918102],
       [-1.29876742, -1.35410379, -1.31442874, -1.32285877],
       [-1.23947943, -1.16734771, -1.17886106, -1.30466512],
       [-1.18019143, -1.16734771, -1.06266019, -1.27737466],
       [-0.99244611, -1.0788843 , -1.14012744, -0.70427491],
       [-0.89363278, -0.70537213, -0.95614272, -0.50414484],
       [-0.97268344, -0.92161602, -1.07234359, -0.64969398],
       [-1.75330872, -1.59983548, -1.46936324, -1.54118248],
       [-1.78295272, -1.69812816, -1.82764926, -1.73221573],
       [-1.6544954 , -1.46222574, -1.79859905, -1.66853798],
       [-1.49639407, -1.58017695, -1.37252918, -1.66853798],
       [-1.12090343, -1.1083721 , -1.32411215, -1.15001916],
       [-1.21971676, -1.29512819, -1.26601171, -1.13182552],
       [-1.5952074 , -1.

In [5]:
pca = PCA(n_components = 1)

pca.fit(temparature_scaled)
temparature_pca = pca.transform(temparature_scaled)
temparature_pca.shape

(181, 1)

In [6]:
pca_columns = ['기온']
df_temparature_pca = pd.DataFrame(temparature_pca, columns = pca_columns)
df_temparature_pca['영등포구'] = df_temparature['영등포구']
df_temparature_pca

기온  영등포구
0    2.904845  2010
1    2.222064  2065
2    2.437038  4356
3    2.532962  4474
4    2.644961  4665
..        ...   ...
176 -3.292701  9246
177 -3.368858  8155
178 -3.361073  9134
179 -3.160806  4408
180 -2.686745   743

[181 rows x 2 columns]

In [7]:
print(pca.explained_variance_ratio_)

[0.97212545]


In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
import numpy as np

In [9]:
rcf = RandomForestRegressor(random_state=156)
scores = cross_val_score(rcf, df_temparature, df['영등포구'], cv = 3)

print('기온 원본 데이터 교차 검증 개별 정확도:' ,scores)
print('기온 원본 데이터 평균 정확도:' ,np.mean(scores))

기온 원본 데이터 교차 검증 개별 정확도: [0.91851331 0.96734827 0.99244415]
기온 원본 데이터 평균 정확도: 0.9594352429231107


# 2. 기온 part

In [10]:
columns = ['평균증기압']
df_pressure = pd.DataFrame(df, columns = columns)
df_pressure['영등포구'] = df['영등포구']
df_pressure

평균증기압  영등포구
0      2.1  2010
1      3.3  2065
2      3.2  4356
3      2.6  4474
4      2.4  4665
..     ...   ...
176   28.3  9246
177   29.5  8155
178   28.8  9134
179   30.4  4408
180   26.6   743

[181 rows x 2 columns]

In [11]:
pressure_scaled = StandardScaler().fit_transform(df_pressure.iloc[:,:-1])
pressure_scaled

array([[-1.03416163],
       [-0.85974021],
       [-0.87427533],
       [-0.96148604],
       [-0.99055627],
       [-0.99055627],
       [-0.97602116],
       [-0.72892414],
       [-0.64171343],
       [-0.72892414],
       [-1.04869675],
       [-1.10683722],
       [-1.0923021 ],
       [-1.0923021 ],
       [-0.9324158 ],
       [-0.90334556],
       [-0.99055627],
       [-1.06323187],
       [-0.90334556],
       [-0.96148604],
       [-0.94695092],
       [-0.87427533],
       [-0.80159974],
       [-0.65624855],
       [-0.46729201],
       [-0.74345926],
       [-0.9324158 ],
       [-0.97602116],
       [-1.01962651],
       [-1.01962651],
       [-0.83066997],
       [-0.71438902],
       [-0.9324158 ],
       [-0.99055627],
       [-1.01962651],
       [-1.07776699],
       [-1.00509139],
       [-0.96148604],
       [-0.88881045],
       [-0.87427533],
       [-0.7725295 ],
       [-0.68531879],
       [-0.74345926],
       [-0.7725295 ],
       [-0.6126432 ],
       [-0

In [12]:
pca = PCA(n_components = 1)

pca.fit(pressure_scaled)
pressure_pca = pca.transform(pressure_scaled)
pressure_pca.shape

(181, 1)

In [13]:
pca_columns = ['기압']
df_pressure_pca = pd.DataFrame(pressure_pca, columns = pca_columns)
df_pressure_pca['영등포구'] = df_pressure['영등포구']
df_pressure_pca

기압  영등포구
0   -1.034162  2010
1   -0.859740  2065
2   -0.874275  4356
3   -0.961486  4474
4   -0.990556  4665
..        ...   ...
176  2.774039  9246
177  2.948461  8155
178  2.846715  9134
179  3.079277  4408
180  2.526942   743

[181 rows x 2 columns]

In [14]:
print(pca.explained_variance_ratio_)

[1.]


In [15]:
rcf = RandomForestRegressor(random_state=156)
scores = cross_val_score(rcf, df_pressure, df['영등포구'], cv = 3)

print('기압 원본 데이터 교차 검증 개별 정확도:' ,scores)
print('기압 원본 데이터 평균 정확도:' ,np.mean(scores))

기압 원본 데이터 교차 검증 개별 정확도: [0.94664646 0.98153209 0.99637479]
기압 원본 데이터 평균 정확도: 0.9748511120553319


# 3. 풍속 part

In [16]:
columns = ['최대순간풍속','최대풍속']
df_windspeed = pd.DataFrame(df, columns = columns)
df_windspeed['영등포구'] = df['영등포구']
df_windspeed

최대순간풍속  최대풍속  영등포구
0       4.5   2.8  2010
1       8.1   4.6  2065
2       6.9   4.1  4356
3       6.8   4.2  4474
4       4.2   2.9  4665
..      ...   ...   ...
176     8.5   5.0  9246
177    13.7   6.0  8155
178    20.9   9.9  9134
179    17.3   9.0  4408
180     9.4   4.6   743

[181 rows x 3 columns]

In [17]:
windspeed_scaled = StandardScaler().fit_transform(df_windspeed.iloc[:,:-1])
windspeed_scaled

array([[-1.76503698, -1.78778972],
       [-0.39489391, -0.37370404],
       [-0.85160826, -0.76650562],
       [-0.88966779, -0.6879453 ],
       [-1.87921557, -1.7092294 ],
       [-0.5090725 , -0.37370404],
       [-1.49862027, -1.63066909],
       [-1.42250121, -1.23786751],
       [-1.72697745, -1.78778972],
       [-0.58519155, -1.31642783],
       [ 1.24166588,  1.66886416],
       [-0.7754892 , -0.6879453 ],
       [ 1.81255882,  1.98310542],
       [-1.07996544, -1.47354846],
       [-1.61279886, -1.55210877],
       [ 0.09987998,  0.49045943],
       [-0.43295344, -0.76650562],
       [-0.96578685, -0.60938499],
       [-0.31877485, -0.29514373],
       [-0.81354873, -0.29514373],
       [-1.57473933, -1.63066909],
       [-1.49862027, -1.31642783],
       [-1.30832262, -1.55210877],
       [ 0.17599904,  0.3333388 ],
       [-0.54713203, -0.1380231 ],
       [-0.54713203, -0.37370404],
       [-0.54713203, -0.76650562],
       [-0.35683438,  0.01909754],
       [-0.20459626,

In [18]:
pca = PCA(n_components = 1)

pca.fit(windspeed_scaled)
windspeed_pca = pca.transform(windspeed_scaled)
windspeed_pca.shape

(181, 1)

In [19]:
pca_columns = ['풍속']
df_windspeed_pca = pd.DataFrame(windspeed_pca, columns = pca_columns)
df_windspeed_pca['영등포구'] = df_windspeed['영등포구']
df_windspeed_pca

풍속  영등포구
0   -2.512228  2010
1   -0.543481  2065
2   -1.144179  4356
3   -1.115541  4474
4   -2.537414  4665
..        ...   ...
176 -0.213630  9246
177  1.741307  8155
178  5.845453  9134
179  4.376661  4408
180 -0.193623   743

[181 rows x 2 columns]

In [20]:
print(pca.explained_variance_ratio_)

[0.97353447]


In [21]:
rcf = RandomForestRegressor(random_state=156)
scores = cross_val_score(rcf, df_windspeed, df['영등포구'], cv = 3)

print('풍속 원본 데이터 교차 검증 개별 정확도:' ,scores)
print('풍속 원본 데이터 평균 정확도:' ,np.mean(scores))

풍속 원본 데이터 교차 검증 개별 정확도: [0.71089097 0.98809808 0.9962912 ]
풍속 원본 데이터 평균 정확도: 0.8984267503010736


# 4. 습도 part

In [23]:
columns = ['최소상대습도','평균상대습도']
df_humidity = pd.DataFrame(df, columns = columns)
df_humidity['영등포구'] = df['영등포구']
df_humidity

최소상대습도  평균상대습도  영등포구
0        31    46.3  2010
1        39    57.9  2065
2        35    58.3  4356
3        28    51.8  4474
4        34    47.6  4665
..      ...     ...   ...
176      79    82.1  9246
177      76    84.4  8155
178      74    81.9  9134
179      89    95.5  4408
180      97    99.3   743

[181 rows x 3 columns]

In [24]:
humidity_scaled = StandardScaler().fit_transform(df_humidity.iloc[:,:-1])
humidity_scaled

array([[-0.49454021, -0.97031874],
       [ 0.01768742, -0.10350122],
       [-0.23842639, -0.07361096],
       [-0.68662557, -0.55932767],
       [-0.30245485, -0.8731754 ],
       [-0.62259711, -0.91053822],
       [-1.13482474, -0.91053822],
       [ 0.65797195,  0.37474293],
       [ 0.46588659,  0.9127676 ],
       [-0.11036949,  0.67364553],
       [ 0.01768742, -0.28284277],
       [-0.30245485, -0.85823027],
       [-0.43051175, -1.00768156],
       [-0.94273938, -1.30658416],
       [ 0.14574432, -0.82086744],
       [-0.62259711, -0.35756842],
       [-0.04634104,  0.04595008],
       [-0.75065402, -0.8507577 ],
       [ 0.7220004 ,  0.97254812],
       [ 0.20977278,  0.31496242],
       [-0.62259711, -0.27537021],
       [-0.43051175, -0.51449228],
       [ 0.27380123, -0.51449228],
       [ 0.33782968, -0.24547995],
       [ 0.78602886,  1.54793562],
       [-0.3664833 ,  0.26265446],
       [-0.49454021, -0.69383384],
       [-0.3664833 , -0.5742728 ],
       [-0.68662557,

In [25]:
pca = PCA(n_components = 1)

pca.fit(humidity_scaled)
humidity_pca = pca.transform(humidity_scaled)
humidity_pca.shape

(181, 1)

In [26]:
pca_columns = ['습도']
df_humidity_pca = pd.DataFrame(humidity_pca, columns = pca_columns)
df_humidity_pca['영등포구'] = df_humidity['영등포구']
df_humidity_pca

습도  영등포구
0   -1.035812  2010
1   -0.060680  2065
2   -0.220644  4356
3   -0.881022  4474
4   -0.831296  4665
..        ...   ...
176  3.029023  9246
177  3.014728  8155
178  2.792080  9134
179  4.189815  4408
180  4.752803   743

[181 rows x 2 columns]

In [27]:
print(pca.explained_variance_ratio_)

[0.95327771]


In [28]:
rcf = RandomForestRegressor(random_state=156)
scores = cross_val_score(rcf, df_humidity, df['영등포구'], cv = 3)

print('습도 원본 데이터 교차 검증 개별 정확도:' ,scores)
print('습도 원본 데이터 평균 정확도:' ,np.mean(scores))

습도 원본 데이터 교차 검증 개별 정확도: [0.85190794 0.98041965 0.9966439 ]
습도 원본 데이터 평균 정확도: 0.9429904968047031


# 5. 운량 part

In [29]:
columns = ['평균전운량','평균중하층운량']
df_cloud = pd.DataFrame(df, columns = columns)
df_cloud['영등포구'] = df['영등포구']
df_cloud

평균전운량  평균중하층운량  영등포구
0      1.4      1.4  2010
1      4.1      4.0  2065
2      4.9      3.6  4356
3      0.0      0.0  4474
4      7.3      1.0  4665
..     ...      ...   ...
176   10.0      7.8  9246
177   10.0      7.8  8155
178   10.0      8.5  9134
179   10.0      7.8  4408
180   10.0      6.4   743

[181 rows x 3 columns]

In [30]:
cloud_scaled = StandardScaler().fit_transform(df_cloud.iloc[:,:-1])
cloud_scaled

array([[-9.73226075e-01, -5.22038613e-01],
       [-9.92540374e-02,  4.69771525e-01],
       [ 1.59700640e-01,  3.17185350e-01],
       [-1.42639676e+00, -1.05609023e+00],
       [ 9.36564674e-01, -6.74624788e-01],
       [-1.42639676e+00, -1.05609023e+00],
       [-1.42639676e+00, -1.05609023e+00],
       [ 4.83393988e-01,  1.19455586e+00],
       [-4.22947385e-01, -1.02426631e-01],
       [ 8.39456669e-01,  2.02745719e-01],
       [-1.29691942e+00, -9.03504051e-01],
       [-5.20055389e-01, -1.05609023e+00],
       [-6.81902062e-01, -3.31305894e-01],
       [-5.84794058e-01, -1.05609023e+00],
       [ 1.32499669e+00,  1.08011623e+00],
       [-9.08487405e-01, -4.45745525e-01],
       [-6.17163393e-01, -1.02426631e-01],
       [-1.32928876e+00, -1.05609023e+00],
       [ 2.24439310e-01,  8.89383507e-01],
       [-1.42639676e+00, -1.05609023e+00],
       [-1.42639676e+00, -1.05609023e+00],
       [ 4.83393988e-01, -6.42800876e-02],
       [ 1.27331306e-01,  2.02745719e-01],
       [ 1.

In [31]:
pca = PCA(n_components = 1)

pca.fit(humidity_scaled)
cloud_pca = pca.transform(cloud_scaled)
cloud_pca.shape

(181, 1)

In [32]:
pca_columns = ['운량']
df_humidity_pca = pd.DataFrame(humidity_pca, columns = pca_columns)
df_humidity_pca['영등포구'] = df_humidity['영등포구']
df_humidity_pca

운량  영등포구
0   -1.035812  2010
1   -0.060680  2065
2   -0.220644  4356
3   -0.881022  4474
4   -0.831296  4665
..        ...   ...
176  3.029023  9246
177  3.014728  8155
178  2.792080  9134
179  4.189815  4408
180  4.752803   743

[181 rows x 2 columns]

In [33]:
print(pca.explained_variance_ratio_)

[0.95327771]


In [34]:
rcf = RandomForestRegressor(random_state=156)
scores = cross_val_score(rcf, df_cloud, df['영등포구'], cv = 3)

print('운량 원본 데이터 교차 검증 개별 정확도:' ,scores)
print('운량 원본 데이터 평균 정확도:' ,np.mean(scores))

운량 원본 데이터 교차 검증 개별 정확도: [0.85817687 0.97035235 0.99700289]
운량 원본 데이터 평균 정확도: 0.9418440340709028
